name: Build and Test PR

permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]
jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      main_branch: 'refs/heads/main'
  build-test:
    uses: ./.github/workflows/build-test-dotnet.yml
    needs: version
    with:
      project_name: PTrampert.SimplePatch
      version: ${{needs.version.outputs.version}}